### PR TITLE
Add missing reducers tests

### PR DESCRIPTION
**Pull request by jenPlusPlus**
@mlimberg

## What's this PR do?

This PR adds missing reducers tests to Reducers.test.js

## Learning
I used my previous tests as a template for my new tests

## Where should the reviewer start?
line 166 in Reducers.test.js

Lines 166 on have new tests that did not exist previously.

Three of my tests do not pass. All three tests deal with removing an item from an array using .filter. This works in the app, but I cannot get the items to be removed from the array in the tests.

## What gif best describes this PR or how it makes you feel?
giphy

### CODE REVIEW

**Comment by NikBorn** [comment]
looks great!
source

**Comment by jenPlusPlus** [comment]
@nicktu12 thanks for the reminder on the console.logs!
@lolakoala i tend to have issues when using .filter / .find on an array of objects. the app performs correctly, but the tests don't remove the item from the array. i'd love to look into it at some point, but probably not today. :)
@NikBorn thanks for the review!

**Comment by mlimberg** [comment]
@jenPlusPlus I see 4 tests passing in the Reducers test file and a couple commented out. I pulled down the latest from your testing branch. Do the tests you're having issues with exist on a different branch? Want to take a look at the filter issue.

**Comment by mlimberg** [comment]
@jenPlusPlus I see 4 tests passing in the Reducers test file and a couple commented out. I pulled down the latest from your testing branch. Do the tests you're having issues with exist on a different branch? Want to take a look at the filter issue.

**Comment by mlimberg** [comment]
@jenPlusPlus I see 4 tests passing in the Reducers test file and a couple commented out. I pulled down the latest from your testing branch. Do the tests you're having issues with exist on a different branch? Want to take a look at the filter issue.

**Comment by mlimberg** [comment]
@jenPlusPlus I see 4 tests passing in the Reducers test file and a couple commented out. I pulled down the latest from your testing branch. Do the tests you're having issues with exist on a different branch? Want to take a look at the filter issue.

**Pull request merged**
